---
title: Tutoring
order: 5
css: tutoring.css
---

The Mathematics Tutoring Center is located in 1S-214.

## Fall 2026

The Mathematics Tutoring Center has tutoring on campus, as well as Distance-based. 
The schedule posts here, and on the door of room 1S-214. Please Check back for frequent updates.

* All hours are in-person unless otherwise indicated.
* For remote sessions: email the tutor during the timeslot indicated to set up tutoring session.
* There is no tutoring on holidays and 'no class' scheduled days

## Tutoring

<table>
    <caption>Weekly tutoring schedule by day, tutor, and time</caption>
    <thead>
        <tr>
            <th scope="col">Day</th>
            <th scope="col">Tutor</th>
            <th scope="col">Time</th>
            <th scope="col">Mode</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row" rowspan="3">Monday</th>
            <td>Raheel</td>
            <td>9:30&nbsp;AM&ndash;12:30&nbsp;PM</td>
            <td>In person</td>
        </tr>
        <tr>
            <td>Ian</td>
            <td>1:20&nbsp;PM&ndash;2:20&nbsp;PM</td>
            <td>In person</td>
        </tr>
        <tr>
            <td>Stivi</td>
            <td>6:30&nbsp;PM&ndash;8:30&nbsp;PM</td>
            <td>In person</td>
        </tr>

        <tr>
            <th scope="row">Tuesday</th>
            <td>Raheel</td>
            <td>2:30&nbsp;PM&ndash;4:30&nbsp;PM</td>
            <td>
                <span class="mode-remote">Remote</span><br>
                <a href="https://bit.ly/4A3Wda9">https://bit.ly/4A3Wda9</a>
            </td>
        </tr>

        <tr>
            <th scope="row" rowspan="3">Wednesday</th>
            <td>Raheel</td>
            <td>9:30&nbsp;AM&ndash;12:30&nbsp;PM</td>
            <td>In person</td>
        </tr>
        <tr>
            <td>Ian</td>
            <td>1:20&nbsp;PM&ndash;4:20&nbsp;PM</td>
            <td>In person</td>
        </tr>
        <tr>
            <td>Stivi</td>
            <td>1:30&nbsp;PM&ndash;4:30&nbsp;PM</td>
            <td>In person</td>
        </tr>

        <tr>
            <th scope="row" rowspan="3">Thursday</th>
            <td>Raheel</td>
            <td>9:30&nbsp;AM&ndash;12:30&nbsp;PM</td>
            <td>In person</td>
        </tr>
        <tr>
            <td>Ian</td>
            <td>12:20&nbsp;PM&ndash;4:20&nbsp;PM</td>
            <td>In person</td>
        </tr>
        <tr>
            <td>Stivi</td>
            <td>2:30&nbsp;PM&ndash;4:30&nbsp;PM</td>
            <td>
                <span class="mode-remote">Remote</span><br>
                <a href="https://bit.ly/4AdIVrD">https://bit.ly/4AdIVrD</a>
            </td>
        </tr>

        <tr>
            <th scope="row" rowspan="2">Friday</th>
            <td>Ian</td>
            <td>12:20&nbsp;PM&ndash;3:50&nbsp;PM</td>
            <td>In person</td>
        </tr>
        <tr>
            <td>Stivi</td>
            <td>12:30&nbsp;PM&ndash;4:30&nbsp;PM</td>
            <td>In person</td>
        </tr>
    </tbody>
</table>

### Tutors

* Ian [ianburek.tutor@gmail.com](mailto:ianburek.tutor@gmail.com)
* Raheel
* Stivi [stivi.tutor.csi@gmail.com](mailto:stivi.tutor.csi@gmail.com)

For further assistance, the [Office of Academic Support](https://www.csi.cuny.edu/students/academic-assistance/tutoring/casa-tutoring-schedule-stem) provides tutoring in the library (Room 1L-117).
