---
title: Undergraduate
---

The Department of Mathematics has around 70 declared majors at any given time and offers around 100 courses each semester for the students of the college.

----

## For Current Students

- [Advising Links/Contacts](advising-resources.qmd)
- [Advising Documents/Program requirements and sample schedules](AdvisingDocuments/)
- [Curriculum description](./course_list.html)
- [Program and Course Description](Major/)
- [Tutoring in Mathematics at CSI](Tutoring)
- [Selected Course Materials](/Resources/)

### Software

- [WebAssign instructions](Courses/WebAssign_Instructions/)
- [WeBWorK Instructions](Courses/WeBWorK_Instructions/)
- [Calculus book guide](calculus-book-guide.qmd)

### External Resources

- [CUNY First listing of all active courses](https://globalsearch.cuny.edu/CFGlobalSearchTool/search.jsp)
- [Grade Appeal](https://csi-undergraduate.catalog.cuny.edu/pages/8GBeppsHt5vr1bmqpDay)
- [Registrar FAQ](https://www.csi.cuny.edu/students/registrar/frequently-asked-questions)
- [Registrar Forms](https://www.csi.cuny.edu/students/registrar/forms-records-update)

## Opportunities & Resources

- [Career opportunities](Career)
- [Simons Undergraduate Lecture Series](simons-undergraduate-lecture-series/)
- [Math Department Awards](Awards/)
- [Independent study courses (MTH594)](independent-study.qmd)
- [Honors Theses](HonorsTheses/)
- [Alumni](Alumni)

## College Resources

- [CSI Major Exploration Tools](https://www.csi.cuny.edu/students/academic-advisement/students/major-exploration-tools)
- [The Teacher Academy](http://www.csi.cuny.edu/teacheracademy)   
- [The Math Club](https://math-csi-cuny.github.io/mathclub)
